name: Deploy

on:
  push:
    branches:
      - main

build:
  name: Build and Deploy
  needs: test
  runs-on: ubuntu-latest

  steps:
    - name: Set up Docker Buildx
      uses: actions/checkout@v3

    - name: use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Deploy to render
      run: |
        curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}